language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - psql -c 'create database foodlove;' -U postgres
# command to run tests
script:
  - pytest --cov

after_success:
  - coveralls
